### ISSUE TITLE
Getting just a white page

### ISSUE THREAD

**Issue by duluca** [aaronksaunders/ionic2GMapNative#1]
Thanks a bunch for putting this together. I'm running your sample with my own API key for iOS, I don't get any errors in xcode or command line, but when I launch the app all I get is a white page and no map. Any ideas on what may be wrong? I do have a cordova test app running the plugin using the same api key, so I don't think that's the issue.

**Comment by aaronksaunders** [comment]
Without seeing something, i have no idea... I need more information

when you open web debugger in safari on the device, what do you see?

## 

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders

This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by macdonaldr93** [comment]
I took a look and found the issue. [Line 39 in home.ts](https://github.com/aaronksaunders/ionic2GMapNative/blob/master/app/pages/home/home.ts#L39) is throwing a type error.

`let myPosition = new GoogleMapsLatLng('38.9072', '-77.0369');`

should be 

`let myPosition = new GoogleMapsLatLng(38.9072, -77.0369);`

**Comment by aaronksaunders** [comment]
@macdonaldr93 thx for tracking that down, there must have been some changes to either ionic-native or the plugin recently since this code actually worked at one point.

looks like in version 1.2.3 of ionic-native, the parameters for lat, lng were strings
https://github.com/driftyco/ionic-native/blob/v1.2.3/src/plugins/googlemaps.ts#L984

**Comment by macdonaldr93** [comment]
@aaronksaunders ah nice. I figured it was something like that. Happy it's resolved!
